    <div style="float:left;position:relative;top:0px;left:0px;text-align:center;width:100%;border-top:1px solid black">
      <br>
    <a href="termsofservice.asp" style="color:black">TERMS OF SERVICE</a> |
    <a href="newarrivals.asp" style="color:black">NEW ARRIVALS</a> |
    <a href="contactus.asp" style="color:black">CONTACT US</a>
    <br>
    Copyright &copy; 2019 AmpleWears, Inc. All Rights Reserved
      </div>
  </body>
</html>